name: Naukri Resume Upload

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 8 AM IST (2:00 UTC)
  workflow_dispatch:     # Allows manual trigger

jobs:
  upload:
    runs-on: windows-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Setup Maven
      - name: Setup Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # 4. Unzip the Selenium Edge profile
      - name: Unzip Selenium profile
        run: |
          Expand-Archive -Path ./selenium-profile/myprofile.zip -DestinationPath ./selenium-profile/myprofile -Force

      # 5. Build Java project
      - name: Build project
        run: mvn clean compile

      # 6. Run Selenium uploader
      - name: Run resume upload
        run: mvn exec:java -Dexec.mainClass="NaukriUploader"
        env:
          PROFILE_PATH: ./selenium-profile/myprofile
          RESUME_PATH: ./resume/AnkurKarna_Resume.pdf
