name: Naukri Resume Upload

on:
  schedule:
    - cron: '0 2 * * *'  # runs daily at 8 AM IST (convert to UTC)
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Unzip Selenium profile
        run: |
          mkdir -p selenium-profile/myprofile
          unzip -o selenium-profile/myprofile.zip -d selenium-profile/myprofile

      - name: Run Selenium uploader
        run: |
          java -cp "path/to/selenium-jars/*:." NaukriUploader
