name: Naukri Resume Upload

on:
  schedule:
    - cron: '0 2 * * *'  # daily at 8 AM IST
  workflow_dispatch:

jobs:
  upload:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Unzip Selenium profile
        run: |
          Expand-Archive -Path ./selenium-profile/myprofile.zip -DestinationPath ./selenium-profile/myprofile -Force

      - name: Build project
        run: mvn clean compile

      - name: Run resume upload
        run: mvn exec:java
